### ISSUE TITLE
Deleting a flow or device in VBX yields error message

### ISSUE THREAD

**Issue by reneighbor** [twilio/OpenVBX#115]
When we try and delete a flow tenant or a device, we get an error message. "An unknown error occurred. Please contact your OpenVBX provider. Unable to complete request: flow/edit/2". This is happening even on v0.91 of OpenVBX.

Install details:
 http://www.factbolt.com/britevbx/index.php/auth/login?redirect=
Hostgator
Apache
2.2.17
PHP
5.2.15 and 5.3.4
(dual environment)
Perl
5.8.8
MySQL
5.1.52

**Comment by geoffschultz** [comment]
I have been running OpenVBX 1.2.13 r79 for years.  I haven't wanted to upgrade due to a call tracking system that I wrote and bolted onto the side of OpenVBX.  Anyhow, everything has been working just fine until today when I tried to save a flow with just a new recording for the greeting I get the same unknown error as described above.  This is a shared server, but I control the version of PHP (5.4.19).  MySQL was recently upgraded upgraded to 5.6.  Any ideas on how to determine what broke/changed/etc?
