### ISSUE TITLE
Call Flow SMS Does Not Work

### ISSUE THREAD

**Issue by ZacharyDuBois** [twilio/OpenVBX#284]
When you have a flow for a call and you have it send an SMS to the caller, it does not work. There are no errors in Twilio's debug console for it either. It does not show up as an outgoing message too. So, the SMS applet seems to be broken in the call flows.

**Comment by kaburkett** [comment]
I am on v1.2.15 r79 and its still an issue. When you have a flow for a call and you direct it to send a SMS to the caller it simply sends nothing (but continues through the flow like it has). This is a key feature I was hoping to see

**Comment by kaburkett** [comment]
@gegere @chadsmith I just tested sending a text during a call (which is what you fixed) and it works wonderfully. However, sending an SMS to the caller still does not work... it is possible that line of code needs updated in more than one place?

**Comment by gegere** [comment]
@kaburkett this is working correctly. I have several installations sending out SMS messages when a call is received. Send me an email and I can help you more.

**Comment by Gipetto** [comment]
It appears that the refactor of #297 to add control structures munged the code. The original was:

```php
if(AppletInstance::getFlowType() == 'voice') $response->sms($sms); else $response->message($sms);
```

which, while correct, didn't adhere to the standards of always using braces. It was updated to this (which is wrong):

```php
if(AppletInstance::getFlowType() == 'voice') 
{
	$response->sms($sms); else $response->message($sms);
}
```

I'm actually not sure what that code will do with the else there.

The updated code should be this so that `->sms()` is used for call flows and `->message()` is used for message flows:

```php
if(AppletInstance::getFlowType() == 'voice') 
{
	$response->sms($sms);
} 
else 
{
	$response->message($sms);
}
```

If someone here can verify this I'll get it merged up in to the develop branch and cut a quick release for `1.2.16`

**Comment by gegere** [comment]
@Gipetto I have updated the code, tested on a installation I use and issued a pull request.

**Comment by Gipetto** [comment]
Updated code in 1.2.16
Closing.

**Comment by mirenkaramta** [comment]
@Gipetto @chadsmith I am using OpenVBX 1.2.20, and facing the same problem after updating the text message content. The call flow doesn't send SMS to the caller, and continues to the next step in the flow. Plese help!
