### ISSUE TITLE
Installation problem - step 5 - "Authenticate"

### ISSUE THREAD

**Issue by jamiecollinson** [twilio/OpenVBX#304]
Trying to install OpenVBX on an Ubuntu 14.04 EC2 instance, and I'm stuck on step 5:

![error message](http://s3.amazonaws.com/awesome_screenshot/6777933?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1418658874&Signature=kltuGvq%2FklPDfqi2oPMazFjEPF8%3D)

Everything except APC and memcache are green on the 1st step (server check). PHP version 5.5.9, MySQL version 5.5.40.

Any way I can diagnose?

**Comment by claytondaley** [comment]
For anyone who finds this in the future, the problem is that Lastpass replaces the value in ALL the password fields.  This includes the passwords on the other "pages" like the database and Twilio API.  To fix it, go back to the previous pages and fix them.

FWIW, I'm sure this could be fixed by changing the way the install pages work (e.g. saving the working values to a JS object when pages are advanced), but it's obviously not a high priority.
